# Generated by Django 4.0.5 on 2022-08-08 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_checklist_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='notes',
            field=models.CharField(default=' ', max_length=300),
        ),
    ]
