# Generated by Django 4.0.5 on 2022-08-08 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_checklist_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='notes',
            field=models.CharField(default='N/A', max_length=300),
        ),
    ]
