# Generated by Django 4.0.5 on 2022-08-16 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_start_date_checklist_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='task_type',
            field=models.CharField(choices=[('HR', 'HR'), ('IT', 'IT')], default='HR', max_length=2),
        ),
        migrations.AlterField(
            model_name='template',
            name='type',
            field=models.CharField(choices=[('onboarding', 'Onboarding'), ('offboarding', 'Offboarding')], default='onboarding', max_length=25),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=50)),
                ('task_type', models.CharField(choices=[('HR', 'HR'), ('IT', 'IT')], default='HR', max_length=2)),
                ('complete', models.BooleanField(default=False)),
                ('checklist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.checklist')),
            ],
        ),
    ]
