# Generated by Django 4.0.5 on 2022-08-16 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_items_task_type_alter_template_type_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklist',
            name='data',
        ),
    ]
