# Generated by Django 4.0.5 on 2022-08-16 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_checklist_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
