# Generated by Django 4.0.5 on 2022-08-17 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_checklist_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='notes',
            field=models.CharField(default='N/A', max_length=500),
        ),
    ]
