# Generated by Django 4.0.5 on 2022-08-17 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_checklist_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='workplace',
        ),
    ]
