# Generated by Django 4.0.5 on 2022-08-30 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_template_workplace'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='type',
            field=models.CharField(choices=[('onboarding', 'Onboarding'), ('offboarding', 'Offboarding')], default='onboarding', max_length=25),
        ),
    ]
